substitutions:
  devicename: "axp"

esphome:
    name: $devicename
    includes:
        - custom_components/axp192/axp192.h

esp32:
  board: ttgo-t-beam
  framework:
    type: arduino

# Enable logging
logger:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 0s

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${devicename}-AP"
    password: "password"
    ap_timeout: 5min

web_server:
  port: 80

i2c:
  - id: bus_a
    sda: GPIO21
    scl: GPIO22
    scan: false

uart:
  rx_pin: GPIO34
  tx_pin: GPIO12
  baud_rate: 9600

button:
  - platform: shutdown
    name: "${devicename} Shutdown"
    id: buttonshutdown
  - platform: restart
    name: "${devicename} Reboot"
    id: buttonreboot

sensor:
  - platform: axp192
    address: 0x34
    i2c_id: bus_a
    update_interval: 60s
    battery_level:
      name: "${devicename} Battery Level"
      id: batterylevel
      accuracy_decimals: 0
    battery_voltage:
      name: "${devicename} Battery Voltage"
      id: batteryvoltage
    temperature:
      name: "${devicename} AXP192 Temperature"
      id: tempAXP192

  - platform: version
    name: "${devicename} ESPHome version"
